kind = "web"
previewPath = "/"
title = "N-Dex"
version = "1.0.0"
id = "artifacts/ndex"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23693

[services.development]
run = "pnpm --filter @workspace/ndex run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ndex", "run", "build" ]
publicDir = "artifacts/ndex/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23693"
BASE_PATH = "/"
